In [1]:
import numpy as np


In [3]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
for i in range(1,10,5):
    print(np.linspace(1,10,i))

[1.]
[ 1.   2.8  4.6  6.4  8.2 10. ]


In [10]:
np.diag(np.ones((2,3)))

array([1., 1.])

In [14]:
np.random.randint(4)

3

In [16]:
vv=np.random.randint(0,10,4)

In [17]:
vv.shape

(4,)

In [18]:
m = np.array([[7,5],[3,6]])
np.linalg.det(m)

27.0

In [19]:
m = np.array([[7,5],[3,6]])
np.linalg.inv(m)

array([[ 0.22222222, -0.18518519],
       [-0.11111111,  0.25925926]])