<a href="https://colab.research.google.com/github/ankurkaiser/Bepec-Training/blob/main/Python_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
n=int(input("enter the number of table : "))
i=1
while i<=10:
  print(n*i)
  i+=1


enter the number of table : 17
17
34
51
68
85
102
119
136
153
170


In [ ]:
#n=int(input("enter a number"))

num=1
n=5
for i in range(0,n):
  for j in range(0,i+1):
    print("*", end= " ")

    num+=1
  print("\r")


* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
num=1
n=5
for i in range(0,n):
  num=1
  for j in range(0,i+1):
    print(num, end= " ")

    num+=1
  print("\r")


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
num=1
n=5
for i in range(0,n):
  for j in range(0,i+1):
    print("WFH", end= " ")

    num+=1
  print("\r")


WFH 
WFH WFH 
WFH WFH WFH 
WFH WFH WFH WFH 
WFH WFH WFH WFH WFH 


In [ ]:
num=1
n=5
for i in range(0,n):
  #num=1
  for j in range(0,i+1):
    print(num, end= " ")

    num+=1
  print("\r")

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


In [ ]:
num=1
n=8
for i in range(0,n):
  for j in range(0,i+1):
    print("*", end=" ")
    num+=1
  print("\r")

for i in range(n,0,-1):
  for j in range(i,0,-1):
    print("*",end=" ")
    num-=1
  print("\r")

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * * * 
* * * * * * * * 
* * * * * * * * 
* * * * * * * 
* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
n=10
for i in range(n,0,-1):
  for j in range(i,0,-1):
    print("*",end=" ")
    num-=1
  print("\r")

* * * * * * * * * * 
* * * * * * * * * 
* * * * * * * * 
* * * * * * * 
* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
import numpy as np

fb=np.array([0,1,1,2,3,5,8,13,21])
fb =fb[1]+fb[0]*fb[-1] 

fb

1

In [ ]:
A="10"

def ad(num):
  A=2
ad(A)
print("A is now", A)


A is now 10


In [ ]:
d1={'Rahul':30,'John':35}
d2={'Rahul':35,'John':40}

d2 > d1

TypeError: ignored

In [ ]:
import requests
from bs4 import BeautifulSoup
 
 
url = 'https://www.geeksforgeeks.org/'
reqs = requests.get(url)
soup = BeautifulSoup(reqs.text, 'html.parser')
 
urls = []
for link in soup.find_all('a'):
    print(link.get('href'))

#main
https://www.geeksforgeeks.org/
https://www.geeksforgeeks.org/analysis-of-algorithms-set-1-asymptotic-analysis/?ref=ghm
https://www.geeksforgeeks.org/analysis-of-algorithms-set-2-asymptotic-analysis/?ref=ghm
https://www.geeksforgeeks.org/analysis-of-algorithms-set-3asymptotic-notations/?ref=ghm
https://www.geeksforgeeks.org/analysis-of-algorithems-little-o-and-little-omega-notations/?ref=ghm
https://www.geeksforgeeks.org/lower-and-upper-bound-theory/?ref=ghm
https://www.geeksforgeeks.org/analysis-of-algorithms-set-4-analysis-of-loops/?ref=ghm
https://www.geeksforgeeks.org/analysis-algorithm-set-4-master-method-solving-recurrences/?ref=ghm
https://www.geeksforgeeks.org/analysis-algorithm-set-5-amortized-analysis-introduction/?ref=ghm
https://www.geeksforgeeks.org/g-fact-86/?ref=ghm
https://www.geeksforgeeks.org/pseudo-polynomial-in-algorithms/?ref=ghm
https://www.geeksforgeeks.org/polynomial-time-approximation-scheme/?ref=ghm
https://www.geeksforgeeks.org/a-time-complexity-question

In [ ]:
mat = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
mat[0,[0,1,2]]

matrix([[1, 2, 3]])

In [ ]:
mat[[0,1,2],0]

matrix([[1],
        [4],
        [7]])

In [ ]:
pt=np.array([1,2,3], ndmin=3)

In [ ]:
pt.shape

(1, 1, 3)

In [ ]:
mat= np.array([[[89,87,79],[69,76,80],[92,87,95]]])

mat.ndim+mat.shape[0]+mat.shape[len(mat.shape)-1]

7

In [ ]:
mat.ndim

3

In [ ]:
mat.shape[0]

1

In [ ]:
mat.shape[len(mat.shape)-1]

3

In [ ]:
len(mat.shape)-1


3

In [ ]:
mat = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
mat[0,[0,1,2]]

matrix([[1, 2, 3]])

In [ ]:
np.matrix([[4.2,3.0,1.3],[5.6,3.1,7.0]], dtype=np.int32)

matrix([[4, 3, 1],
        [5, 3, 7]], dtype=int32)

In [ ]:
np.matrix([[4,3,1],[5,3,7.0]])

matrix([[4., 3., 1.],
        [5., 3., 7.]])

In [ ]:
mat[0]

matrix([[1, 2, 3]])

In [ ]:
np.array([[4.2,3.0,1.3],[5.6,3.1,7.0]], dtype=np.int32)

array([[4, 3, 1],
       [5, 3, 7]], dtype=int32)

In [ ]:
import pandas as pd
import numpy as np
ser=pd.Series(np.linspace(10,100))

In [ ]:
ser.describe()

count     50.000000
mean      55.000000
std       26.774779
min       10.000000
25%       32.500000
50%       55.000000
75%       77.500000
max      100.000000
dtype: float64

In [ ]:
df = pd.DataFrame(ser)
df.describe()

0
count   50.000000
mean    55.000000
std     26.774779
min     10.000000
25%     32.500000
50%     55.000000
75%     77.500000
max    100.000000

In [ ]:
dict1= {1:2,3:4}

for i,j in dict1.items():
  print(i,j)

1 2
3 4


In [5]:
def students(name,age,*company):
  print("Name :", name)
  print("Age :", age)
  print("Company :",company)

students("Ankur",28,"Infosys","Bepec")

Name : Ankur
Age : 28
Company : ('Infosys', 'Bepec')


In [13]:
def student(name,age,**company):
  print("Name :", name)
  print("Age :", age)
  print("Company :",company)

student(name="Ankur",age=28,company1="Infosys",company2="Bepec",company3="XYZ Solutions")


Name : Ankur
Age : 28
Company : {'company1': 'Infosys', 'company2': 'Bepec', 'company3': 'XYZ Solutions'}


In [16]:
def student(name,age,**company):
  print("Name :", name)
  print("Age :", age)
  print("Company :",company)
  for i,j in company.items():
    print(i,":",j)

In [17]:
student(name="Ankur",age=28,company1="Infosys",company2="Bepec",company3="XYZ Solutions")

Name : Ankur
Age : 28
Company : {'company1': 'Infosys', 'company2': 'Bepec', 'company3': 'XYZ Solutions'}
company1 : Infosys
company2 : Bepec
company3 : XYZ Solutions


In [ ]:
``